<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class NumberOfWeekendsTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Storage::fake('public');
    }

    /** @test */
    public function it_displays_input_form()
    {
        $this->get(route('weekend-tracker.create'))->assertSuccessful()->assertSee('start_date')->assertSee('end_date');
    }

    /** @test */
    public function it_requires_a_start_date()
    {
        $this->post(route('weekend-tracker.store'), ['start_date' => ''])->assertSessionHasErrors(['start_date']);
    }

    /** @test */
    public function it_requires_a_start_date_to_be_a_valid_date()
    {

        $this->post(route('weekend-tracker.store'),
            ['start_date' => 'invalid_date'])->assertSessionHasErrors(['start_date']);
    }

    /** @test */
    public function it_accepts_a_valid_date()
    {
        $this->post(route('weekend-tracker.store'),
            ['start_date' => '2020-10-06'])->assertSessionDoesntHaveErrors(['start_date']);
    }

    /** @test */
    public function it_requires_an_end_date()
    {
        $this->post(route('weekend-tracker.store'), ['end_date' => ''])->assertSessionHasErrors(['end_date']);
    }

    /** @test */
    public function it_requires_a_end_date_to_be_a_valid_date()
    {
        $this->post(route('weekend-tracker.store'),
            ['end_date' => 'invalid_date'])->assertSessionHasErrors(['end_date']);
    }

    /** @test */
    public function it_requires_a_end_date_to_occur_after_start_date()
    {
        $this->post(route('weekend-tracker.store'),
            ['start_date' => '2020-10-11', 'end_date' => '2020-10-10'])->assertSessionHasErrors(['end_date']);
    }

    /** @test */
    public function it_accepts_a_end_date()
    {
        $this->post(route('weekend-tracker.store'),
            ['end_date' => '2020-10-06'])->assertSessionDoesntHaveErrors(['end_date']);
    }

    /** @test */
    public function it_returns_success_message_when_calculated()
    {
        $dates = [
            'start_date' => '2020-10-01',
            'end_date' => '2020-10-08',
        ];
        $this->post(route('weekend-tracker.store'), $dates)->assertRedirect(route('weekend-tracker.create'));
    }

}
